baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "我的博客"
theme = "airtest"

[params]
description = "我的个人博客"
favicon = "favicon.ico"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "关于"
    url = "/about"
    weight = 2

[[params.social]]
icon = "fa-github"
url = "https://github.com/yourusername"

[permalinks]
posts = "/:year/:month/:title/"

[build]
writeStats = true
noJSConfigInAssets = true

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]
admin = "/admin/:slug/"
